### ISSUE TITLE
Cannot parse some unusual epithets

### ISSUE THREAD

**Issue by dimus** [gnames/gnparser#199]
From #191 by @KatjaSchulz:
Names with strange epithets that end up in an unparsed tail:

Seleuca chûjôi Voss, 1957
Peperomia non-alata Trel.
Hyacinthoides non-scripta (L.) Chouard ex Rothm.
Monocelis non-scripta Curini-Galletti, 2014
Macromitrium st.-johnii E. B. Bartram, 1940

**Comment by abubelinha** [comment]
From https://github.com/gnames/gnparser/issues/191#issuecomment-912966149

> ```
> Names with seemingly innocuous epithets that nevertheless end up in an unparsed tail:
> 
> Profusulinella оblопgа Potievskaya, 1964
> Tetrataxis toгosus Postoyalko, 1975
> Anomalina badkhyseпsis Kuryleva, 1973
> Bigenerina iпfrapaleogenica Suleymanov, 1963
> Carpelimus (Trogophloeus) rougemoпti Gildenkov, 2014
> ```
> 
> All of these contain cyrillic characters that not suppose to be in scientific names: `п`, `г`, so they are not parsed correctly
> 
> I bet whoever entered them was in the middle of replying to their instant message :D

> All of these contain cyrillic characters that not supposed to be in scientific names: `п`, `г`, so they are not parsed correctly
> 
> I bet whoever entered them was in the middle of replying to their instant message :D

Those cyrillic characters do so much resemble **n** and **r** Latin characters. Very difficult to detect them when looking at an excel file. Would it be possible for gnparser to automatically detect and replace them for their Latin "resembled equivalents", and rise a quality warning "Non-standard characters in canonical"?

Much like it already happens to **ñ** (parsing "Anthyllis pe**ñ**alarensis Vázquez", returns species:"pe**n**alarensis" and canonical "Anthyllis pe**n**alarensis").

A similar approach could be used for _chûjôi_ epithet above: change **úùûü** into **u**, **óòôöø** into **o**, and so on ...

**Comment by abubelinha** [comment]
This leads me to the question of [double-vowel characters](https://en.wikipedia.org/wiki/Ligature_(writing)#%C3%86_and_%C5%92).
These are not frequent but I have seen them before in some documents and spradsheets in my institution.
Example: Hierochl**œ** instead of Hierochl**oe**
Mmm ... now I see this could be more tricky than I thought above, since I see gnparser is already replacing **ö** into **oe** (instead of **o**)

**Comment by dimus** [comment]
> Those cyrillic characters do so much resemble n and r Latin characters. Very difficult also to detect them when looking at an excel file, for example.
>Would it be perhaps possible for gnparser to automatically detect and replace them for their Latin "resembled equivalents", and rise a quality warning "Non-standard characters in canonical"?

I found that it is wise to step at some point of trying to "fix" apparent problems in the name. For example GNparser does not try to parse names with capitalized epithets, or with low-case genera (unless it is exclicitly required by setting). Otherwise the amount of false positives becomes too big, and really bad names get into datasets.

It  is a judgement call what to parse and what not to parse, and often it is just an intuition. There are a few diacritics that used to be legal in scientific names, these are "allowed" to a degree, but cyrillic letters never were allowed, so I consider them to be an unparseable mistake.

**Comment by dimus** [comment]
> Seleuca chûjôi Voss, 1957

I think this name belongs to unpaseable category

**Comment by dimus** [comment]
> This leads me to the question of double-vowel characters.

Sadly there is no good solution. Some letters are easy like `œ` as almost everyboy (and the codes) normalize them the same way to `oe`.
Other diacritcis are very tricky

1. The rules abour their transliteration are confusing and depend on a country of the name author as well as the year when the name was published
2.  People transliterate these names differently in different datasets, so sometimes `ö` is transliterated to `o` and sometimes to `oe` for the same name-string.

**Comment by abubelinha** [comment]
Sorry, I was editing my original comment while you answered, and finished and posted later on.

In summary, for the `ö` case, I think the `o` is a much more conservative approach than `oe`.

New comment now:

As there could be different opinions about this, I wonder if in a future version it could be possible to feed gnparser with an array of replacements (i.e. a config file, or something we can post through the api) so we can force it to turn `ö` into `o` (instead of `oe`), `п` into `n`, `г` into `r`, and so on (a user choice to override defaults).

I don't think I will ever need to parse names with those cyrillic characters, but perhaps this (keyboard-originated / OCR-originated) problem could be frequent in some scenarios, and it would be good letting gnparser correct this when we know it's happening.

Thanks

**Comment by abubelinha** [comment]
Regarding some of the strange epithets which cannot be parsed, I have just found that "Lychnis flos-cuculi L." is correctly parsed.
So the problem in _non-scripta_ and _st.-johnii_ epithets seems to be the `non` or `st.` substrings, rather than the `-` symbol
